-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.search_index
(
    title text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    source_table text COLLATE pg_catalog."default",
    source_id text COLLATE pg_catalog."default",
    search_vector tsvector GENERATED ALWAYS AS ((setweight(to_tsvector('english'::regconfig, COALESCE(title, ''::text)), 'A'::"char") || setweight(to_tsvector('english'::regconfig, COALESCE(description, ''::text)), 'B'::"char"))) STORED,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone
);

CREATE TABLE IF NOT EXISTS public.search_index_config
(
    k text COLLATE pg_catalog."default" NOT NULL,
    v text COLLATE pg_catalog."default",
    CONSTRAINT idx_24727_sqlite_autoindex_search_index_config_1 PRIMARY KEY (k)
);

CREATE TABLE IF NOT EXISTS public.search_index_content
(
    id bigint NOT NULL,
    c0 text COLLATE pg_catalog."default",
    c1 text COLLATE pg_catalog."default",
    c2 text COLLATE pg_catalog."default",
    c3 text COLLATE pg_catalog."default",
    CONSTRAINT idx_24717_search_index_content_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.search_index_data
(
    id bigint NOT NULL,
    block bytea,
    CONSTRAINT idx_24707_search_index_data_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.search_index_docsize
(
    id bigint NOT NULL,
    sz bytea,
    CONSTRAINT idx_24722_search_index_docsize_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.search_index_idx
(
    segid text COLLATE pg_catalog."default" NOT NULL,
    term text COLLATE pg_catalog."default" NOT NULL,
    pgno text COLLATE pg_catalog."default",
    CONSTRAINT idx_24712_sqlite_autoindex_search_index_idx_1 PRIMARY KEY (segid, term)
);
END;