-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.product_variants
(
    id bigserial NOT NULL,
    product_id bigint,
    sku text COLLATE pg_catalog."default",
    price bigint,
    stripe_price_id text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT idx_24758_product_variants_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attribute_value_product_variant
(
    attribute_value_id bigint NOT NULL,
    product_variant_id bigint NOT NULL,
    CONSTRAINT idx_24765_sqlite_autoindex_attribute_value_product_variant_1 PRIMARY KEY (attribute_value_id, product_variant_id)
);

CREATE TABLE IF NOT EXISTS public.attribute_values
(
    id bigserial NOT NULL,
    attribute_id bigint,
    value text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT idx_24750_attribute_values_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.attributes
(
    id bigserial NOT NULL,
    name text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    data_type text COLLATE pg_catalog."default" DEFAULT 'string'::text,
    CONSTRAINT idx_24741_attributes_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.attribute_value_product_variant
    ADD CONSTRAINT attribute_value_product_variant_attribute_value_id_fkey FOREIGN KEY (attribute_value_id)
    REFERENCES public.attribute_values (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.attribute_value_product_variant
    ADD CONSTRAINT attribute_value_product_variant_product_variant_id_fkey FOREIGN KEY (product_variant_id)
    REFERENCES public.product_variants (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.attribute_values
    ADD CONSTRAINT attribute_values_attribute_id_fkey FOREIGN KEY (attribute_id)
    REFERENCES public.attributes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;